//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineTicketOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canceled_flights
    {
        public int ID { get; set; }
        public Nullable<int> flight_ID { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
