//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineTicketOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateFlight
    {
        public int ID { get; set; }
        public Nullable<int> flight_id { get; set; }
        public string departure_day { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
        public string arrival_day { get; set; }
        public Nullable<System.TimeSpan> arrival_time { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
