//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineTicketOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_class_info
    {
        public int class_ID { get; set; }
        public Nullable<int> flight_ID { get; set; }
        public string service_class { get; set; }
        public Nullable<int> count_places { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
