//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineTicketOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_ID { get; set; }
        public Nullable<int> Place_ID { get; set; }
        public string Passenger_ID { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
        public string isCanceled { get; set; }
        public string isExpired { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Place Place { get; set; }
    }
}
